### ISSUE TITLE
Want to pass variables from CI into Dokku app

### ISSUE THREAD

**Issue by alexgleason** [dokku/ci-docker-image#26]
I'm using this image to deploy **review apps**, and... [it works](https://gitlab.com/soapbox-pub/soapbox-be/-/merge_requests/146)!

But my application also wants a `DOMAIN` envvar to know its own host name. This would naturally come **from the CI env itself.**

I could probably do something like this:

```yml
script:
  - dokku-deploy
  - ssh dokku@$DOKKU_HOST/$CI_ENVIRONMENT_SLUG -- config:set $CI_ENVIRONMENT_SLUG DOMAIN=${CI_ENVIRONMENT_SLUG}.dokku.soapbox.pub
```

But it's a bit awkward. I kind of wish I could do this before `dokku-deploy`, but then `setup-ssh` wouldn't have been run, so it wouldn't have my key.

I wish this image provided a generic `dokku` command that I could use like regular dokku and it would "just work".

I ended up using `app.json` to make it connect to my database and that worked great. This is the only thing I'm missing.

**Comment by josegonzalez** [comment]
I wonder if there is a way for us to inject commands before the deploy section, but after any review apps were created. Maybe a good way to do this would be by exposing dokku commands via a file? Something like this:

```shell
#!/bin/sh -l
# this file is bin/ci-pre-deploy
# the env var `REMOTE_APP_NAME` and `SSH_REMOTE` are exposed to the script
ssh "$SSH_REMOTE" config:set "$REMOTE_APP_NAME" DOMAIN=review.dokku.soapbox.pub

# any other command runs as normal
echo "hi"
```

That file is then executed like so:

```shell
chmod +x bin/ci-pre-deploy
REMOTE_APP_NAME="remote_app_name" SSH_REMOTE="$ssh_remote" bin/ci-pre-deploy
```

In this way, the ci instructions aren't ci-specific (so you can move from Jenkins to Github Actions, for example) and can expand to do really any setup someone would want for their dokku app prior to the deploy.

**Comment by josegonzalez** [comment]
The implementation was slightly different re: env vars, but seems good.

**Comment by alexgleason** [comment]
Awesome, thank you!!
