### ISSUE TITLE
SSH_HOSTKEY description and  ssh-keyscan in do not match bin/setup.ssh do not match

### ISSUE THREAD

**Issue by aehm03** [dokku/ci-docker-image#38]
## Description of problem
I could not deploy (via gitlab-ci pipeline) from the docker image because of an ssh authentication problem. The ssh logs on the server said:
```
Unable to negotiate with <ip> port 22: no matching host key type found.
```
Turns out the description of `SSH_HOSTKEY`  in `README.MD` (`ssh-keyscan -t rsa $HOST`) does describe correctly whats happening in `bin/setup.ssh`– the `-t rsa` parameter is missing. When running `ssh-keyscan` manually and storing the result in the variable, the deployment works. 

### How reproducible
I could reproduce the problems from the ci pipeline in an docker image.
### Steps to Reproduce

1. Setup dokku with private ssh key (`ssh-rsa`). (I used an digital ocean droplet which runs `SSH-2.0-OpenSSH_8.2p1`, don't know if this is part of the problem though.)
2. Run ci docker image and add private key to it. 
4. Run the keyscan from `setup.ssh`:  
```
ssh-keyscan -H -p 22 $dokku-server >/root/.ssh/known_hosts
chmod 600 "/root/.ssh/known_hosts"
```
5. Try ssh-login at dokku server: `ssh dokku@host` **does not work**
6. Re-run keyscan with parameter according to docs: `ssh-keyscan -t rsa -H -p 22 $dokku-server >/root/.ssh/known_hosts`
7. **ssh works now**

(Same goes for the ci-pipeline, if I the value of keyscan with `-t rsa` is added as `SSH_HOSTKEY`, the pipeline works.

**Comment by josegonzalez** [comment]
When you say "run the keyscan from `setup.ssh`", are you manually running this? Can you provide a ci config that does work and one that doesn't?

**Comment by aehm03** [comment]
Yes I ran things manually (inside the ci-docker-image) to test the difference. The difference between working and non-working ci was not the in the config, which is pretty simple:
```
deploy_develop:
  stage: deploy
  image: dokku/ci-docker-image
  
  variables:
    GIT_DEPTH: "0"
    GIT_REMOTE_URL:  <some url>
  
  before_script: []
  script:
    - dokku-deploy 
  after_script:
    - dokku-unlock
```
but in adding the results of `ssh-keyscan -t rsa -H -p 22 $my-dokku-server` to the gitlab-ci variable `SSH_HOST_KEY`. 
Reason why this works is that this avoids the else branch of `/bin/setup-ssh`:
```
if [ -n "$SSH_HOST_KEY" ]; then
  log-info "Adding SSH_HOST_KEY to known_hosts"
  echo "$SSH_HOST_KEY" >>"/root/.ssh/known_hosts"
  chmod 600 "/root/.ssh/known_hosts"
else
  ssh_port=$(parse-ssh-port)
  ssh_host=$(parse-ssh-host)

  log-info "Generating SSH_HOST_KEY from ssh-keyscan against $ssh_host:$ssh_port"
  ssh-keyscan -H -p "$ssh_port" "$ssh_host" >>/root/.ssh/known_hosts
  chmod 600 "/root/.ssh/known_hosts"
fi
``` 
which does this keyscan by itself.

**Comment by josegonzalez** [comment]
Sorry, so what is the fix here? To change our bin/setup-ssh?

**Comment by aehm03** [comment]
Ok I did some googling and found out that this is not really the fault of the setup script. Ssh-keyscan seems to be a bit unreliable because of networking and different server/client versions of open-ssh. 

One thing should be changed definately: the readme says `ssh-keyscan -t rsa` is used but this is (rightfully) not the case.

The other things are:
* we could add a timeout flag to the keyscan, like proposed here: https://unix.stackexchange.com/questions/346376/ssh-keyscan-has-no-output
* we could check whether `/root/.ssh/known_hosts` is empty afterwards and exit with an error that is more telling.

**Comment by josegonzalez** [comment]
What timeout worked for you?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any follow-up. The code seems to work fine for me in my testing, so I am guessing there is something specific to the user's setup that we haven't diagnosed.

Feel free to comment with more information so we can improve the project and I'll reopen.
