### ISSUE TITLE
Dokku-unlock command is missing the dokku binary

### ISSUE THREAD

**Issue by benr77** [dokku/ci-docker-image#58]
## Description of problem

Unlock command does not work

### How reproducible

In Gitlab CI, I have

```
    after_script:
        - dokku-unlock
```

This binary runs the following command:

```
ssh -p "$ssh_port" "dokku@$ssh_host" apps:unlock "$app"
```

#### Actual Results

This errors with `bash: line 1: apps:unlock: command not found`

#### Expected Results

It does not error

### Solution

I think it's missing the `dokku` binary, so 

```
ssh -p "$ssh_port" "dokku@$ssh_host" apps:unlock "$app"
```

should become

```
ssh -p "$ssh_port" "dokku@$ssh_host" dokku apps:unlock "$app"
```

Thanks

**Comment by josegonzalez** [comment]
I think you setup your ssh key incorrectly on the host. How did you add it? If you added it directly to `/home/dokku/.ssh/authorized_keys`, that is incorrect. You'll need to remove the key and add it via `dokku ssh-keys:add` instead.

See [this doc](https://dokku.com/docs/deployment/user-management/) for more details.

**Comment by benr77** [comment]
Yes, good catch. Thanks for the help and the quick response!
