### ISSUE TITLE
Incorrect default value for BRANCH in readme

### ISSUE THREAD

**Issue by nerg4l** [dokku/ci-docker-image#7]
The readme states the following about `BRANCH`:

> - `BRANCH`:
>   - description: The branch to deploy when pushing to Dokku
>   - required: false
>   - default: ''master

The default value for `BRANCH` is not 'master'. It is the branch which triggers the CI pipeline.

**Comment by josegonzalez** [comment]
No, that should be `CI_BRANCH_NAME`. Regardless, we had the wrong default for `BRANCH`, so I fixed that.

**Comment by AndrewKvalheim** [comment]
Got bitten by a similar misunderstanding… I expected the default to be the checked out branch, not some hard coded one.
